HospitalProject/Models/Notification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalProject.Models
{
    public class Notification
    {

        [Key]
        public int NotificationID { get; set; }

        [Required, StringLength(255), Display(Name = "Notification Title")]
        public string NotificationTitle { get; set; }

        [Required, StringLength(2000), Display(Name = "Notification Text")]
        public string NotificationText { get; set; }

        [Required, Display(Name = "Notification Start Date")]
        public DateTime NotificationStartDate { get; set; }

        [Required, Display(Name = "Notification End Date")]
        public DateTime NotificationEndDate { get; set; }

        [Required, Display(Name = "Notification Created Date")]
        public DateTime NotificationCreatedDate { get; set; }

        [Required, Display(Name = "Notification Updated Date")]
        public DateTime NotificationUpdatedDate { get; set; }

        [Required, Display(Name = "isEnabled")]
        public bool IsPublished { get; set; }

        [Required, Display(Name = "isDeleted")]
        public bool IsDeleted { get; set; }

        [ForeignKey("AdminID")]
        public int AdminID { get; set; }

        public virtual Admin Admin { get; set; }
    }
}

HospitalProject/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HospitalProject.Data;
using HospitalProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace HospitalProject.Controllers
{
    public class NotificationController : Controller
    {
        private readonly HospitalDbContext db;
        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public NotificationController(HospitalDbContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _env = env;
            _userManager = usermanager;
        }

        // GET: Notification
        public async Task<IActionResult> Index(int pageNum)
        {
            var user = await GetCurrentUserAsync();
            // From Christine's Pagination Notes
            var _notifications = await db.Notifications.ToListAsync();
            int pageCount = _notifications.Count();
            int perPage = 5;
            int maxPage = (int)Math.Ceiling((decimal)pageCount / perPage) - 1;
            if (maxPage < 0) maxPage = 0;
            if (pageNum < 0) pageNum = 0;
            if (pageNum > maxPage) pageNum = maxPage;
            int start = perPage * pageNum;

            ViewData["pageNum"] = (int)pageNum;
            ViewData["paginationSummary"] = "";

            if (maxPage > 0)
            {
                ViewData["paginationSummary"] = (pageNum + 1).ToString() + " of " + (maxPage + 1).ToString();
            }
            List<Notification> notifications = await db.Notifications.Skip(start).Take(perPage).ToListAsync();


            if (user != null)
            {
                if (user.AdminID == null)
                {
                    ViewData["UserHasAdmin"] = "False";
                }
                else
                {
                    ViewData["UserHasAdmin"] = user.AdminID.ToString();
                }
                return View(notifications);
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
                return View(notifications);
            }
        }

        // GET: Notification/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notification = await db.Notifications
                .Include(n => n.Admin)
                .SingleOrDefaultAsync(m => m.NotificationID == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }

        // GET: Notification/Create
        public IActionResult Create()
        {
            Notification notification = new Notification();
            notification.NotificationCreatedDate = DateTime.Today;
            notification.NotificationUpdatedDate = DateTime.Today;
            ViewData["AdminID"] = new SelectList(db.Admins, "AdminID", "FirstName");
            return View(notification);
        }

        // POST: Notification/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NotificationID,NotificationTitle,NotificationText,NotificationStartDate,NotificationEndDate,NotificationCreatedDate,NotificationUpdatedDate,IsPublished,IsDeleted,AdminID")] Notification notification)
        {
            if (ModelState.IsValid)
            {
                db.Add(notification);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdminID"] = new SelectList(db.Admins, "AdminID", "FirstName", notification.AdminID);
            return View(notification);
        }

        // GET: Notification/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notification = await db.Notifications.SingleOrDefaultAsync(m => m.NotificationID == id);
            if (notification == null)
            {
                return NotFound();
            }
            ViewData["AdminID"] = new SelectList(db.Admins, "AdminID", "FirstName", notification.AdminID);
            return View(notification);
        }

        // POST: Notification/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NotificationID,NotificationTitle,NotificationText,NotificationStartDate,NotificationEndDate,NotificationCreatedDate,NotificationUpdatedDate,IsPublished,IsDeleted,AdminID")] Notification notification)
        {
            if (id != notification.NotificationID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(notification);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotificationExists(notification.NotificationID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdminID"] = new SelectList(db.Admins, "AdminID", "FirstName", notification.AdminID);
            return View(notification);
        }

        // GET: Notification/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var notification = await db.Notifications
                .Include(n => n.Admin)
                .SingleOrDefaultAsync(m => m.NotificationID == id);
            if (notification == null)
            {
                return NotFound();
            }

            return View(notification);
        }

        // POST: Notification/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var notification = await db.Notifications.SingleOrDefaultAsync(m => m.NotificationID == id);
            db.Notifications.Remove(notification);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotificationExists(int id)
        {
            return db.Notifications.Any(e => e.NotificationID == id);
        }
    }
}

HospitalProject/Views/Notification/Create.cshtml
@model HospitalProject.Models.Notification

@{
    ViewData["Title"] = "Create";

}

<h4>Add New Notification</h4>
<form action="/Notification/Create" method="post" novalidate="novalidate">
    <div id="LinkForm">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="NotificationTitle">Notification Title</label>
                    <input class="form-control" type="text" data-val="true" data-val-length="The field Notification Title must be a string with a maximum length of 255." data-val-length-max="255" data-val-required="The Notification Title field is required." id="NotificationTitle" name="NotificationTitle" value="">
                    <span class="text-danger field-validation-valid" data-valmsg-for="NotificationTitle" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="NotificationText">Notification Text</label>
                    <input class="form-control" type="text" data-val="true" data-val-length="The field Notification Text must be a string with a maximum length of 2000." data-val-length-max="2000" data-val-required="The Notification Text field is required." id="NotificationText" name="NotificationText" value="">
                    <span class="text-danger field-validation-valid" data-valmsg-for="NotificationText" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    @Html.TextBoxFor(model => model.NotificationCreatedDate, new { @value = System.DateTime.Now, @class = "form-control", @type = "hidden", })
                    <span class="text-danger field-validation-valid" data-valmsg-for="NotificationCreatedDate" data-valmsg-replace="true"></span>
                    @Html.TextBoxFor(model => model.NotificationUpdatedDate, new { @value = System.DateTime.Now, @class = "form-control", @type = "hidden", })
                    <span class="text-danger field-validation-valid" data-valmsg-for="NotificationUpdatedDate" data-valmsg-replace="true"></span>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-val="true" data-val-required="The isPublished field is required." id="IsPublished" name="IsPublished" value="true"> isPublished
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-val="true" data-val-required="The isDeleted field is required." id="IsDeleted" name="IsDeleted" value="true"> isDeleted
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="NotificationStartDate">Notification Start Date</label>
                    <input class="form-control valid" type="datetime-local" data-val="true" data-val-required="The Notification Start Date field is required." id="NotificationStartDate" name="NotificationStartDate" value="0001-01-01T00:00:00.000" aria-describedby="NotificationStartDate-error" aria-invalid="false">
                    <span class="text-danger field-validation-valid" data-valmsg-for="NotificationStartDate" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="NotificationEndDate">Notification End Date</label>
                    <input class="form-control valid" type="datetime-local" data-val="true" data-val-required="The Notification End Date field is required." id="NotificationEndDate" name="NotificationEndDate" value="0001-01-01T00:00:00.000" aria-describedby="NotificationEndDate-error" aria-invalid="false">
                    <span class="text-danger field-validation-valid" data-valmsg-for="NotificationEndDate" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <label asp-for="AdminID" class="control-label"></label>
                <select asp-for="AdminID" class="form-control" asp-items="ViewBag.AdminID"></select>
            </div>
        </div>
        <input name="__RequestVerificationToken" type="hidden" value="CfDJ8FF-moBai2dDuR_fKqpaXgs3AJljfSt1ufikH5VSAofUQ4FivME9TrM3RSm0JhwRYlf6xbQcbZgfaBxMDF3B1oYlyy33oU2_iIphd5UmXSDZh-NH37IJq0l4nsCjxUwCJmXoheqH6rEJrqisua2x_eBUm6SymZ2_UHKN1ykms_ZXB5oLbi6Jojme6mRX6Gxhlg">
        <input type="submit" value="Add Notification" class="btn btn-primary" />
    </div>
</form>
<!--
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NotificationTitle" class="control-label"></label>
                <input asp-for="NotificationTitle" class="form-control" />
                <span asp-validation-for="NotificationTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationText" class="control-label"></label>
                <input asp-for="NotificationText" class="form-control" />
                <span asp-validation-for="NotificationText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationStartDate" class="control-label"></label>
                <input asp-for="NotificationStartDate" class="form-control" />
                <span asp-validation-for="NotificationStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationEndDate" class="control-label"></label>
                <input asp-for="NotificationEndDate" class="form-control" />
                <span asp-validation-for="NotificationEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationCreatedDate" class="control-label"></label>
                <input asp-for="NotificationCreatedDate" class="form-control" />
                <span asp-validation-for="NotificationCreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationUpdatedDate" class="control-label"></label>
                <input asp-for="NotificationUpdatedDate" class="form-control" />
                <span asp-validation-for="NotificationUpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="AdminID" class="control-label"></label>
                <select asp-for="AdminID" class ="form-control" asp-items="ViewBag.AdminID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
-->

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProject/Views/Notification/Delete.cshtml
@model HospitalProject.Models.Notification

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Notification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NotificationTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationText)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationStartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationStartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationEndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationEndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationCreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationCreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationUpdatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationUpdatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Admin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Admin.FirstName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NotificationID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HospitalProject/Views/Notification/Details.cshtml
@model HospitalProject.Models.Notification

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Notification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NotificationTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationText)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationStartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationStartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationEndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationEndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationCreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationCreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NotificationUpdatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotificationUpdatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Admin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Admin.FirstName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NotificationID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HospitalProject/Views/Notification/Edit.cshtml
@model HospitalProject.Models.Notification

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Notification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NotificationID" />
            <div class="form-group">
                <label asp-for="NotificationTitle" class="control-label"></label>
                <input asp-for="NotificationTitle" class="form-control" />
                <span asp-validation-for="NotificationTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationText" class="control-label"></label>
                <input asp-for="NotificationText" class="form-control" />
                <span asp-validation-for="NotificationText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationStartDate" class="control-label"></label>
                <input asp-for="NotificationStartDate" class="form-control" />
                <span asp-validation-for="NotificationStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationEndDate" class="control-label"></label>
                <input asp-for="NotificationEndDate" class="form-control" />
                <span asp-validation-for="NotificationEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationCreatedDate" class="control-label"></label>
                <input asp-for="NotificationCreatedDate" class="form-control" />
                <span asp-validation-for="NotificationCreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NotificationUpdatedDate" class="control-label"></label>
                <input asp-for="NotificationUpdatedDate" class="form-control" />
                <span asp-validation-for="NotificationUpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="AdminID" class="control-label"></label>
                <select asp-for="AdminID" class="form-control" asp-items="ViewBag.AdminID"></select>
                <span asp-validation-for="AdminID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProject/Views/Notification/Index.cshtml
@model IEnumerable<HospitalProject.Models.Notification>

@{
    ViewData["Title"] = "Index";
}

<h4>Emergency Notifications</h4>

<p>
    @{ //variable declaration id (will put user admin id into here)
        string id = "";
    }
    @if ((string)ViewData["UserHasAdmin"] == "False")
    {
        <div>Only Admins can create and view Notifications. Please login as Admin. </div>
    }
    else if ((string)ViewData["UserHasAdmin"] == "None")
    {
        <div>Please @Html.ActionLink("Log In", "Login", "Account") or @Html.ActionLink("Register An Account", "Register", "Account") to create new notifications</div>
    }
    else
    {
        id = (string)ViewData["UserHasAdmin"];
        <a href="Notification/Create"><button class="btn btn-primary">Add New Notification</button></a>

        <div>
            <!-- From Christine's Pagination Notes -->
            @ViewData["PaginationSummary"]
            @Html.ActionLink("Prev", "Index", "Link",
                new { pagenum= ((int)ViewData["pagenum"] - 1)}
                )
            |
            @Html.ActionLink("Next", "Index", "Notification",
                new { pagenum = ((int)ViewData["pagenum"] + 1) }
                )
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NotificationTitle)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NotificationText)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NotificationStartDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NotificationEndDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NotificationCreatedDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NotificationUpdatedDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsPublished)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsDeleted)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Admin)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotificationTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotificationText)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotificationStartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotificationEndDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotificationCreatedDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotificationUpdatedDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsPublished)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsDeleted)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Admin.FirstName)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.NotificationID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.NotificationID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.NotificationID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</p>