HospitalProject/Models/ReachUs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalProject.Models
{
    public class ReachUs
    {
        [Key]
        public int ReachUsID { get; set; }

        [Required, StringLength(50), Display(Name = "First Name")]
        public string FName { get; set; }

        [Required, StringLength(50), Display(Name = "Last Name")]
        public string LName { get; set; }

        /*[Required, Display(Name = "Phone Number")]
        public int Phone { get; set; }*/

        /* https://stackoverflow.com/questions/28904826/phone-number-validation-mvc 
        * I have used stackoverflow to get a way to have a regular expression on the method to validate the phone number
        */
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Phone Number")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Wrong phone number")]
        public string Phone { get; set; }

        [Required, StringLength(100), Display(Name ="Email")]
        public string Email { get; set; }

        [StringLength(500), Display(Name ="Comment")]
        public string Comment { get; set; }

        [ForeignKey("AdminID")]
        public int AdminID { get; set; }

        public virtual Admin Admin { get; set; }


    }
}

HospitalProject/Controllers/ReachUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using HospitalProject.Models;
using HospitalProject.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace HospitalProject.Controllers
{
    public class ReachUsController : Controller
    {
        private readonly HospitalDbContext db;
        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public ReachUsController(HospitalDbContext context,IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _env = env;
            _userManager = usermanager;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public async Task<ActionResult> List(int pagenum)
        {
            var _reachus = await db.Reach_Us.Include(a=> a.Admin).ToListAsync();
            int reachuscount = _reachus.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)reachuscount / perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if (maxpage > 0)
            {
                ViewData["PaginationSummary"] = (pagenum + 1).ToString() + " of " + (maxpage + 1).ToString();

            }
            List<ReachUs> reachUs = await db.Reach_Us.Include(a=>a.Admin).Skip(start).Take(perpage).ToListAsync();

            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
                return View(await db.Reach_Us.ToListAsync());
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
                return View(await db.Reach_Us.ToListAsync());
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("FName, LName, Phone, Email, Comment")] ReachUs reachUs)
        {
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); // forbid becasue no user is logged in
            if (user.AdminID == null) return Forbid(); // because admin account is not logged in
            if (ModelState.IsValid)
            {
                reachUs.AdminID = user.AdminID.GetValueOrDefault();
                reachUs.Admin = user.Admin;
                db.Reach_Us.Add(reachUs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reachUs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("AdminID,ReachUsID,FName,LName,Phone,Email,Comment")] ReachUs reachUs)
        {
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid();
            if (user.AdminID != reachUs.AdminID)
            {
                return Forbid();
            }
            if (ModelState.IsValid)
            {
                db.Entry(reachUs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reachUs);
        }


        public async Task<ActionResult> Edit(int? id, int? adminid)
        {
            if (id == null || adminid == null)
            {
                return new StatusCodeResult(400);
            }
            ReachUs reachUs = db.Reach_Us.Find(id);
            if (reachUs == null)
            {
                return NotFound();
            }

            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); // forbid because no user logged in
            if (user.AdminID != adminid)
            {
                return Forbid(); // forbid because they have the wrong account
            }
            return View(reachUs);
        }

        public async Task<ActionResult> Details(int? id, int? adminid)
        {
            if (id == null || adminid == null)
            {
                return new StatusCodeResult(400);
            }
            ReachUs reachUs = db.Reach_Us.Find(id);
            if (reachUs == null)
            {
                return NotFound();
            }

            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid();
            if (user.AdminID != adminid)
            {
                return Forbid();
            }
            return View(reachUs);
        }

        public async Task<ActionResult> Delete(int? id, int? adminid)
        {
            if (id == null || adminid == null)
            {
                return new StatusCodeResult(400);
            }
            ReachUs reachUs = db.Reach_Us.Find(id);
            if (reachUs == null)
            {
                return NotFound();
            }

            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid();
            if (user.AdminID != adminid)
            {
                return Forbid();
            }
            return View(reachUs);
        }

        /* This action is to delete a country from the Country Table after pressing submit button
         and return to Country/Index
        */
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id, int adminid)
        {
            var user = await GetCurrentUserAsync();
            if (user.AdminID != adminid)
            {
                return Forbid();
            }
            ReachUs reachUs = db.Reach_Us.Find(id);
            db.Reach_Us.Remove(reachUs);
            db.SaveChanges();
            return RedirectToAction("Index"); // To go back to Country/Index 

        }
    }
}

HospitalProject/Views/ReachUs/Create.cshtml
@model HospitalProject.Models.ReachUs

@{
    ViewData["Title"] = "Create";
}

<h2>Add a Specialist</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Specialist</h3>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalProject/Views/ReachUs/Delete.cshtml
@model HospitalProject.Models.ReachUs
@{
    ViewData["Title"] = "Delete";
}
<div class="title">
    <h2>Delete</h2>

    <h3>Are you sure you want to Delete this Form?</h3>
</div>

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="center">
            <input type="submit" value="Delete" id="submit" />
        </div>
        <div class="center">
            <button class="buttonLink">@Html.ActionLink("Back to Forms list", "Index")</button>
        </div>
    }
</div>

HospitalProject/Views/ReachUs/Details.cshtml
@model HospitalProject.Models.ReachUs
@{
    ViewData["Title"] = "Details";
}

<div class="title">
    <h2>Details</h2>
    <div class="row">
        <div class="col-md-12" style="border: 1px solid #cecece; border-radius:15px;">
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.FName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.FName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.LName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.LName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Phone):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.Phone)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Email):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.Email)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Comment):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.Comment)
                </div>
            </div>

            <div>
                <button class="buttonLink">@Html.ActionLink("Back to Reach us Forms List", "Index")</button>
            </div>
        </div>
    </div>
</div>

HospitalProject/Views/ReachUs/Edit.cshtml
@model HospitalProject.Models.ReachUs
@{
    ViewData["Title"] = "Edit";
}

<h2 class="title">Edit</h2>


@using (Html.BeginForm("Edit", "ReachUs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Specialist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReachUsID)
        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalProject/Views/ReachUs/Index.cshtml
@model IEnumerable<HospitalProject.Models.ReachUs>
@{
    ViewData["Title"] = "Index";
}

<h2 class="title">Reach Us</h2>

<div class="title btn-md">@Html.ActionLink("Reach Us Form", "Create")</div>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-12" style="border: 1px solid #cecece; border-radius:15px;">
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.FName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.FName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.LName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.LName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.Phone):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Phone)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.Email):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Email)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.Comment):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Comment)
                </div>
            </div>
            <div>
                <div class="center">
                    <button class="buttonLink">@Html.ActionLink("Edit", "Edit", new { id = item.ReachUsID })</button>
                    <button class="buttonLink">@Html.ActionLink("Details", "Details", new { id = item.ReachUsID })</button>
                    <button class="buttonLink">@Html.ActionLink("Delete", "Delete", new { id = item.ReachUsID })</button>
                </div>
            </div>
        </div>

    }
</div>

HospitalProject/Views/ReachUs/List.cshtml
@model IEnumerable<HospitalProject.Models.ReachUs>
@{
    ViewData["Title"] = "Index";
}

<h2 class="title">Reach Us</h2>

<div class="title btn-md">
    @{
        string id = "";
    }
    @if ((string)ViewData["UserHasAdmin"] == "False")
    {
        @Html.ActionLink("Add Admin", "Create", "Admin")
    }
    else if ((string)ViewData["UserHasAdmin"] == "None")
    {
        @Html.ActionLink("Register An Account", "Register", "Account")
    }
    else
    {
        @Html.ActionLink("Your Profile", "Details/" + (string)ViewData["UserHasAdmin"], "Admin")
        id = (string)ViewData["UserHasAdmin"];
        <div>
            @Html.ActionLink("Reach Us", "Create", "ReachUs")
        </div>
    }
</div>

<div class="reccontainer" style="overflow:hidden;">
    <div>
        @ViewData["PaginationSummary"]
        @Html.ActionLink("Prev","List","ReachUs", new { pagenum = ((int)ViewData["pagenum"] - 1)  }
        ) | @Html.ActionLink("Next","List","ReachUs", new { pagenum = ((int)ViewData["pagenum"]+1) }
)

    </div>

</div>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-12" style="border: 1px solid #cecece; border-radius:15px;">
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.FName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.FName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.LName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.LName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.Phone):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Phone)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.Email):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Email)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(modelItem => item.Comment):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Comment)
                </div>
            </div>
            <div>
                <div class="center">
                    <button class="buttonLink">@Html.ActionLink("Edit", "Edit", new { id = item.ReachUsID })</button>
                    <button class="buttonLink">@Html.ActionLink("Details", "Details", new { id = item.ReachUsID })</button>
                    <button class="buttonLink">@Html.ActionLink("Delete", "Delete", new { id = item.ReachUsID })</button>
                </div>
            </div>
        </div>

    }
</div>