HospitalProject/Models/Link.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace HospitalProject.Models
{
    public class Link
    {
        [Key]
        public int LinkID { get; set; }

        [Required, StringLength(255), Display(Name = "Link Text")]
        public string LinkText { get; set; }

        [Required, StringLength(255), Display(Name = "Link Type")]
        public string LinkType { get; set; }

        [Required, StringLength(255), Display(Name = "External URL")]
        public string LinkExternalURL { get; set; }

        [Required, Display(Name = "Created Date")]
        public DateTime LinkCreatedDate { get; set; }

        [Required, Display(Name = "Modified Date")]
        public DateTime LinkUpdatedDate { get; set; }

        [Required, Display(Name = "isEnabled?")]
        public bool IsPublished { get; set; }

        [Required, Display(Name = "isDeleted?")]
        public bool IsDeleted { get; set; }

        [ForeignKey("PageID")]
        public int PageID { get; set; }

        public virtual Page page { get; set; }
    }
}

HospitalProject/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HospitalProject.Data;
using HospitalProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace HospitalProject.Controllers
{
    public class LinkController : Controller
    {
        private readonly HospitalDbContext db;
        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public LinkController(HospitalDbContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
             db = context;
            _env = env;
            _userManager = usermanager;
        }

        // GET: Link
        public async Task<IActionResult> Index(int pageNum)
        {
            var user = await GetCurrentUserAsync();

            var _links = await db.Links.ToListAsync();
            int linkCount = _links.Count();
            int perPage = 5;
            int maxPage = (int)Math.Ceiling((decimal)linkCount / perPage) - 1;
            if (maxPage < 0) maxPage = 0;
            if (pageNum < 0) pageNum = 0;
            if (pageNum > maxPage) pageNum = maxPage;
            int start = perPage * pageNum;

            ViewData["pageNum"] = (int)pageNum;
            ViewData["paginationSummary"] = "";

            if (maxPage > 0)
            {
                ViewData["paginationSummary"] = (pageNum + 1).ToString() + " of " + (maxPage + 1).ToString();
            }

            List<Link> links = await db.Links.Skip(start).Take(perPage).ToListAsync();


            if (user != null)
            {
                if (user.AdminID == null)
                {
                    ViewData["UserHasAdmin"] = "False";
                }
                else
                {
                    ViewData["UserHasAdmin"] = user.AdminID.ToString();
                }
                return View(links);
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
                return View(links);
            }
        }

        // GET: Link/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var link = await db.Links
                .Include(l => l.page)
                .SingleOrDefaultAsync(m => m.LinkID == id);
            if (link == null)
            {
                return NotFound();
            }

            return View(link);
        }

        // GET: Link/Create
        public IActionResult Create()
        {
            Link link = new Link();
            link.LinkCreatedDate = DateTime.Today;
            link.LinkUpdatedDate = DateTime.Today;
            ViewData["PageID"] = new SelectList(db.Pages, "PageID", "PageTitle");
            return View(link);
        }

        // POST: Link/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LinkID,LinkText,LinkType,LinkExternalURL,LinkCreatedDate,LinkUpdatedDate,IsPublished,IsDeleted,PageID")] Link link)
        {
            if (ModelState.IsValid)
            {
                db.Add(link);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PageID"] = new SelectList(db.Pages, "PageID", "PageContent", link.PageID);
            return View("Error");
        }

        // GET: Link/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var link = await db.Links.SingleOrDefaultAsync(m => m.LinkID == id);
            if (link == null)
            {
                return NotFound();
            }
            ViewData["PageID"] = new SelectList(db.Pages, "PageID", "PageContent", link.PageID);
            return View(link);
        }

        // POST: Link/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LinkID,LinkText,LinkType,LinkExternalURL,LinkCreatedDate,LinkUpdatedDate,IsPublished,IsDeleted,PageID")] Link link)
        {
            if (id != link.LinkID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(link);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LinkExists(link.LinkID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PageID"] = new SelectList(db.Pages, "PageID", "PageContent", link.PageID);
            return View(link);
        }

        // GET: Link/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var link = await db.Links
                .Include(l => l.page)
                .SingleOrDefaultAsync(m => m.LinkID == id);
            if (link == null)
            {
                return NotFound();
            }

            return View(link);
        }

        // POST: Link/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var link = await db.Links.SingleOrDefaultAsync(m => m.LinkID == id);
            db.Links.Remove(link);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LinkExists(int id)
        {
            return db.Links.Any(e => e.LinkID == id);
        }
    }
}

HospitalProject/Views/Link/Create.cshtml
@model HospitalProject.Models.Link

@{
    ViewData["Title"] = "Create";
}


<h4>Create New Link</h4>

<form action="/Link/Create" method="post" novalidate="novalidate">
    <div id="LinkForm">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="LinkText">Link Text</label>
                    <input class="form-control" type="text" data-val="true" data-val-length="The field Link Text must be a string with a maximum length of 255." data-val-length-max="255" data-val-required="The Link Text field is required." id="LinkText" name="LinkText" value="">
                    <span class="text-danger field-validation-valid" data-valmsg-for="LinkText" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="LinkType">Select Type of Link</label>
                    <select class="form-control valid" data-val="true" data-val-required="The Link Type field is required." id="LinkType" name="LinkType" aria-describedby="LinkType-error" aria-invalid="false">
                        <option value="1">Internal</option>
                        <option value="2">External</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="LinkExternalURL">External URL</label>
                    <input class="form-control" type="text" data-val="true" data-val-length="The field External URL must be a string with a maximum length of 255." data-val-length-max="255" data-val-required="The External URL field is required." id="LinkExternalURL" name="LinkExternalURL" value=" ">
                    <span class="text-danger field-validation-valid" data-valmsg-for="LinkExternalURL" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label" for="PageID">Internal Page</label>
                    <select asp-for="PageID" class="form-control" asp-items="ViewBag.PageID"></select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-group">
                    @Html.TextBoxFor(model => model.LinkCreatedDate, new { @value = System.DateTime.Now, @class = "form-control", @type = "hidden" })
                    <span class="text-danger field-validation-valid" data-valmsg-for="LinkCreatedDate" data-valmsg-replace="true"></span>
                    @Html.TextBoxFor(model => model.LinkUpdatedDate, new { @value = System.DateTime.Now, @class = "form-control", @type = "hidden" })
                    <span class="text-danger field-validation-valid" data-valmsg-for="LinkUpdatedDate" data-valmsg-replace="true"></span>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-val="true" data-val-required="The isPublished field is required." id="IsPublished" name="IsPublished" value="true"> isPublished
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-val="true" data-val-required="The isDeleted field is required." id="IsDeleted" name="IsDeleted" value="true"> isDeleted
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input name="__RequestVerificationToken" type="hidden" value="CfDJ8FF-moBai2dDuR_fKqpaXgs3AJljfSt1ufikH5VSAofUQ4FivME9TrM3RSm0JhwRYlf6xbQcbZgfaBxMDF3B1oYlyy33oU2_iIphd5UmXSDZh-NH37IJq0l4nsCjxUwCJmXoheqH6rEJrqisua2x_eBUm6SymZ2_UHKN1ykms_ZXB5oLbi6Jojme6mRX6Gxhlg">
        <input type="submit" value="Add Link" class="btn btn-primary" />
    </div>
</form>

<!--
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LinkText" class="control-label"></label>
                <input asp-for="LinkText" class="form-control" />
                <span asp-validation-for="LinkText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkType" class="control-label"></label>
                <input asp-for="LinkType" class="form-control" />
                <span asp-validation-for="LinkType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkExternalURL" class="control-label"></label>
                <input asp-for="LinkExternalURL" class="form-control" />
                <span asp-validation-for="LinkExternalURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkCreatedDate" class="control-label"></label>
                <input asp-for="LinkCreatedDate" class="form-control" />
                <span asp-validation-for="LinkCreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkUpdatedDate" class="control-label"></label>
                <input asp-for="LinkUpdatedDate" class="form-control" />
                <span asp-validation-for="LinkUpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PageID" class="control-label"></label>
                <select asp-for="PageID" class="form-control" asp-items="ViewBag.PageID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
-->
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProject/Views/Link/Delete.cshtml
@model HospitalProject.Models.Link

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Link</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LinkText)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkExternalURL)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkExternalURL)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkCreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkCreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkUpdatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkUpdatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.page)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.page.PageContent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LinkID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HospitalProject/Views/Link/Details.cshtml
@model HospitalProject.Models.Link

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Link</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LinkText)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkExternalURL)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkExternalURL)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkCreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkCreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkUpdatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkUpdatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.page)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.page.PageContent)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LinkID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HospitalProject/Views/Link/Edit.cshtml
@model HospitalProject.Models.Link

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Link</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LinkID" />
            <div class="form-group">
                <label asp-for="LinkText" class="control-label"></label>
                <input asp-for="LinkText" class="form-control" />
                <span asp-validation-for="LinkText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkType" class="control-label"></label>
                <input asp-for="LinkType" class="form-control" />
                <span asp-validation-for="LinkType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkExternalURL" class="control-label"></label>
                <input asp-for="LinkExternalURL" class="form-control" />
                <span asp-validation-for="LinkExternalURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkCreatedDate" class="control-label"></label>
                <input asp-for="LinkCreatedDate" class="form-control" />
                <span asp-validation-for="LinkCreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkUpdatedDate" class="control-label"></label>
                <input asp-for="LinkUpdatedDate" class="form-control" />
                <span asp-validation-for="LinkUpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsPublished" /> @Html.DisplayNameFor(model => model.IsPublished)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PageID" class="control-label"></label>
                <select asp-for="PageID" class="form-control" asp-items="ViewBag.PageID"></select>
                <span asp-validation-for="PageID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HospitalProject/Views/Link/Index.cshtml
@model IEnumerable<HospitalProject.Models.Link>

@{
    ViewData["Title"] = "Index";
}

<h4>Links</h4>

<p>
    @{ //variable declaration id (will put user admin id into here)
        string id = "";
    }
    @if ((string)ViewData["UserHasAdmin"] == "False")
    {
        <div>Only Admins can create and view Links. Please login as Admin. </div>
    }
    else if ((string)ViewData["UserHasAdmin"] == "None")
    {
        <div>Please @Html.ActionLink("Log In", "Login", "Account") or @Html.ActionLink("Register An Account", "Register", "Account") to create new navigation links</div>
    }
    else
    {
        id = (string)ViewData["UserHasAdmin"];
        <a href="Link/Create"><button class="btn btn-primary">Add New Link</button></a>

        <div>
            <!-- From Christine's Pagination Notes -->
            @ViewData["PaginationSummary"]
            @Html.ActionLink("Prev", "Index", "Link",
                new { pagenum= ((int)ViewData["pagenum"] - 1)}
                )
            |
            @Html.ActionLink("Next", "Index", "Link",
                new { pagenum = ((int)ViewData["pagenum"] + 1) }
                )
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.LinkText)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LinkType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LinkExternalURL)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LinkCreatedDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LinkUpdatedDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsPublished)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsDeleted)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.page)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.LinkText)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LinkType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LinkExternalURL)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LinkCreatedDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LinkUpdatedDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsPublished)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsDeleted)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.page.PageContent)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.LinkID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.LinkID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.LinkID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }


</p>