HospitalProject/Models/JobPosting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalProject.Models
{
    public class JobPosting
    {
        [Key]
        public int JobPostingID { get; set; }

        [Required, StringLength(255), Display(Name = "Title")]
        public string Title { get; set; }

        [Required, StringLength(255), Display(Name = "Description")]
        public string Description { get; set; }

        [Required, StringLength(255), Display(Name = "Qualifications")]
        public string Qualifications { get; set; }

        [Required, Display(Name = "Date Posted")]
        public DateTime DatePosted{ get; set; }

        [Required, Display(Name = "Deadline")]
        public DateTime Deadline { get; set; }

        [Required, Display(Name = "Is Active")]
        public bool IsActive { get; set; }

        [ForeignKey("DeparmentID")]
        public int DepartmentID { get; set; }

        public virtual Department Department { get; set; }

        [ForeignKey("AdminID")]
        public int AdminID { get; set; }

        public virtual Admin Admin { get; set; }
    }
}

HospitalProject/Controllers/JobPostingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using HospitalProject.Models;
using HospitalProject.Models.ViewModels;
using HospitalProject.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using System.Data.SqlClient;

// Based off Christine's Example

namespace HospitalProject.Controllers
{
    public class JobPostingController : Controller
    {
        private readonly HospitalDbContext db;
        private readonly IHostingEnvironment _env;

        private readonly UserManager<ApplicationUser> _userManager;
        private async Task<ApplicationUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(HttpContext.User);

        public JobPostingController(HospitalDbContext context, IHostingEnvironment env, UserManager<ApplicationUser> usermanager)
        {
            db = context;
            _env = env;
            _userManager = usermanager;
        }

        // Returns a List View of Job Postings
        public async Task<ActionResult> Index(int pageNum)
        {
            var user = await GetCurrentUserAsync();

            // From Christine's Pagination Notes
            var _jobPostings = await db.JobPostings.Include(jp => jp.Admin).Include(jp => jp.Department).ToListAsync();

            // If the visitor is not an admin only consider active postings
            if (user == null || user.AdminID == null)
            {
                for (int i = 0; i < _jobPostings.Count(); i++)
                {
                    if (_jobPostings[i].IsActive == false)
                    {
                        _jobPostings.Remove(_jobPostings[i]);
                    }
                }
            }

            int jpCount = _jobPostings.Count();
            int perPage = 5;
            int maxPage = (int)Math.Ceiling((decimal)jpCount / perPage) - 1;
            if (maxPage < 0) maxPage = 0;
            if (pageNum < 0) pageNum = 0;
            if (pageNum > maxPage) pageNum = maxPage;
            int start = perPage * pageNum;

            ViewData["pageNum"] = (int)pageNum;
            ViewData["paginationSummary"] = "";

            if (maxPage > 0)
            {
                ViewData["paginationSummary"] = (pageNum + 1).ToString() + " of " + (maxPage + 1).ToString();
            }

            // If the user is an admin user send all job postings to the view, otherwise send only active job postings
            if (user != null)
            {
                if (user.AdminID == null) {
                    ViewData["UserHasAdmin"] = "False";
                    return View(_jobPostings.Skip(start).Take(perPage));
                }
                else {
                    ViewData["UserHasAdmin"] = user.AdminID.ToString();
                    List<JobPosting> jobPostings = await db.JobPostings.Include(jp => jp.Admin).Skip(start).Take(perPage).ToListAsync();
                    return View(jobPostings);
                }
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
                return View(_jobPostings.Skip(start).Take(perPage));
            }
        }

        // Returns a Detail View for a Single Job Posting
        public async Task<ActionResult> Details(int? id, int? adminid)
        {
            if (id == null || adminid == null)
            {
                return new StatusCodeResult(400);
            }
            JobPosting jobPosting = db.JobPostings.Include(jp => jp.Admin).SingleOrDefault(jp => jp.JobPostingID == id);

            if (jobPosting == null)
            {
                return NotFound();
            }

            var user = await GetCurrentUserAsync();

            if (user != null)
            {
                if (user.AdminID == null) { ViewData["UserHasAdmin"] = "False"; }
                else { ViewData["UserHasAdmin"] = user.AdminID.ToString(); }
            }
            else
            {
                ViewData["UserHasAdmin"] = "None";
            }

            return View(jobPosting);
        }
        
        // Return the Create View for Job Postings
        public ActionResult Create()
        {
            return View(db.Departments.ToList());
        }

        // After the Create form is submitted
        // Insert a new entry into the JobPostings table and return the list view
        [HttpPost]
        public async Task<ActionResult> Create(string job_title, string job_desc, string job_qual, 
            string job_deadline_date, string job_deadline_time, string job_is_active, string job_department)
        {
            string deadline = job_deadline_date + " " + job_deadline_time;
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); //forbid because they don't have an account
            if (user.AdminID == null) return Forbid(); //forbid because no admin account

            string queryString = "INSERT INTO jobpostings (Title, Description, Qualifications, DatePosted, Deadline, IsActive, DepartmentID, AdminID) " +
                "VALUES (@title, @desc, @qual, @postdate, @deadline, @active, @deptid, @adminid)";

            SqlParameter[] queryParams = new SqlParameter[8];
            queryParams[0] = new SqlParameter("@title", job_title);
            queryParams[1] = new SqlParameter("@desc", job_desc);
            queryParams[2] = new SqlParameter("@qual", job_qual);
            queryParams[3] = new SqlParameter("@postdate", DateTime.Now);
            queryParams[4] = new SqlParameter("@deadline", DateTime.Parse(deadline));
            // If the active checkbox is checked set @active to true, otherwise false
            queryParams[5] = job_is_active != null ? new SqlParameter("@active", true) : new SqlParameter("@active", false);
            queryParams[6] = new SqlParameter("@deptid", int.Parse(job_department));
            queryParams[7] = new SqlParameter("@adminid", user.AdminID);

            db.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("Index");
        }

        // Return the Edit View for a particular Job Posting
        public async Task<ActionResult> Edit(int? id, int? adminid)
        {
            if (id == null || adminid == null)
            {
                return new StatusCodeResult(400);
            }
            JobPosting jobPosting = db.JobPostings.Find(id);
            JobPostingEdit jpEditView = new JobPostingEdit();

            if (jobPosting== null)
            {
                return NotFound();
            }

            jpEditView.JobPosting = jobPosting;
            jpEditView.Departments = db.Departments.ToList();

            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); //forbid because they have no account
            if (user.AdminID != adminid)
            {
                return Forbid(); //forbid because they have the wrong account
            }
            return View(jpEditView);
        }

        // After the Edit Form is Submitted
        // Edit an existing entry in the JobPostings Table and return the Details view for that particular posting
        [HttpPost]
        public async Task<ActionResult> Edit(int? id, string job_title, string job_desc, string job_qual,
            string job_deadline_date, string job_deadline_time, string job_is_active, string job_department)
        {
            if ((id == null) || (db.JobPostings.Find(id) == null))
            {
                return new StatusCodeResult(400);
            }

            string deadline = job_deadline_date + " " + job_deadline_time;
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); //forbid because they don't have an account
            if (user.AdminID == null) return Forbid(); //forbid because no admin account

            string queryString = "UPDATE jobpostings SET Title=@title, Description=@desc, Qualifications=@qual, " +
                "Deadline=@deadline, IsActive=@active, DepartmentID=@deptid, AdminID=@adminid WHERE JobPostingID=@jpid";

            SqlParameter[] queryParams = new SqlParameter[8];
            queryParams[0] = new SqlParameter("@title", job_title);
            queryParams[1] = new SqlParameter("@desc", job_desc);
            queryParams[2] = new SqlParameter("@qual", job_qual);
            queryParams[3] = new SqlParameter("@deadline", DateTime.Parse(deadline));
            queryParams[4] = job_is_active != null ? new SqlParameter("@active", true) : new SqlParameter("@active", false);
            queryParams[5] = new SqlParameter("@deptid", int.Parse(job_department));
            queryParams[6] = new SqlParameter("@adminid", user.AdminID);
            queryParams[7] = new SqlParameter("@jpid", id);

            db.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("Details", new { id, adminid = user.AdminID });
        }

        // Return the Delete View for a particular Job Posting
        public async Task<ActionResult> Delete(int? id, int? adminid)
        {
            if (id == null || adminid == null)
            {
                return new StatusCodeResult(400);
            }

            JobPosting jobPosting = await db.JobPostings.Include(jp => jp.Department).SingleOrDefaultAsync(jp => jp.JobPostingID == id);
            if (jobPosting == null)
            {
                return NotFound();
            }
            var user = await GetCurrentUserAsync();
            if (user == null) return Forbid(); // forbid because they haven't logged in
            if (user.AdminID != adminid)
            {
                return Forbid(); //forbid because they are are the wrong person
            }
            return View(jobPosting);
        }

        // After the delete is confirmed

HospitalProject/Views/JobPosting/Create.cshtml
@model IEnumerable<HospitalProject.Models.Department>

@{
    ViewData["Title"] = "Create";
}

<h2>Add a Job Posting</h2>

<!-- Form to create a new Job Posting -->
<form method="POST" action="/JobPosting/Create">
    <div class="form-row">
        <label for="job-title">Job Title: </label>
        <input type="text" id="job-title" name="job_title" />
    </div>

    <div class="form-row">
        <label for="job-desc">Job Description: </label>
        <textarea id="job-desc" name="job_desc"></textarea>
    </div>

    <div class="form-row">
        <label for="job-qual">Job Qualifications: </label>
        <textarea id="job-qual" name="job_qual"></textarea>
    </div>

    <div class="form-row">
        <label>Deadline: </label>
        <input type="date" name="job_deadline_date" />
        <input type="time" name="job_deadline_time" />
    </div>

    <div class="form-row">
        <label for="job-is-active">Is Active?: </label>
        <input type="checkbox" id="job-is-active" name="job_is_active" value="true">
    </div>

    <div class="form-row">
        <label for="job-department">Department:</label>
        <!-- Creates a dropdown list with all the departments -->
        <select id="job-department" name="job_department">
            @foreach (var department in Model)
            {
                <option value="@department.DepartmentID">@department.Name</option>
            }
        </select>
    </div>

    <div class="form-row">
        <input type="submit" value="Submit" />
    </div>
</form>

@Html.ActionLink("Back to List", "Index", "JobPosting")

HospitalProject/Views/JobPosting/Delete.cshtml
@model HospitalProject.Models.JobPosting

@{
    ViewBag.Title = "Delete";
}

<h2>Are you sure you want to delete this job posting?</h2>

<div>
    <div>Title : @Model.Title</div>
    <div>Description : @Model.Description</div>
    <div>Qualifications : @Model.Qualifications</div>
    <div>Date Posted : @Model.DatePosted.ToString()</div>
    <div>Deadline : @Model.Deadline.ToString()</div>
    <div>Is Active? : @Model.IsActive.ToString()</div>
    <div>Department : @Model.Department.Name</div>
    
    <form method="POST" action="/JobPosting/Delete/@Model.JobPostingID">
        <input type="hidden" name="admin_id" value="@Model.AdminID" />

        <div class="form-row">
            <input type="submit" value="Delete" />
        </div>
    </form>

    <div>@Html.ActionLink("Back to List", "Index", "JobPosting")</div>
</div>

HospitalProject/Views/JobPosting/Details.cshtml
@model HospitalProject.Models.JobPosting

@{
    ViewData["Title"] = "Edit";
}

<h2>Job Details</h2>

@if ((string)ViewData["UserHasAdmin"] != "False" && (string)ViewData["UserHasAdmin"] != "None")
{
    <div>@Html.ActionLink("Edit", "Edit", new { id = @Model.JobPostingID, adminid = @Model.AdminID })</div>
    <div>@Html.ActionLink("Delete", "Delete", new { id = @Model.JobPostingID, adminid = Model.AdminID })</div>
}

    <div class="event-details">
        <h2>Title: @Model.Title</h2>
        <div class="feature-description">Department: @Model.Department</div>
        <div class="feature-description">Description: @Model.Description</div>
        <div class="feature-description">Qualifications: @Model.Qualifications</div>
        <div class="feature-description">Deadline to Apply: @Model.Deadline.ToString()</div>

        @if ((string)ViewData["UserHasAdmin"] != "False" && (string)ViewData["UserHasAdmin"] != "None")
        {
            <div class="feature-description">Is Active?: @Model.IsActive.ToString()</div>
            <div class="feature-description">Created By: @Model.Admin.FirstName.ToString() @Model.Admin.LastName.ToString()</div>
        }
    </div>

<div>@Html.ActionLink("Back to List", "Index", "JobPosting")</div>

HospitalProject/Views/JobPosting/Edit.cshtml
@model HospitalProject.Models.ViewModels.JobPostingEdit

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit a Job Posting</h2>

<!-- Form to edit a Job Posting -->
<form method="POST" action="/JobPosting/Edit/@Model.JobPosting.JobPostingID">
    <div class="form-row">
        <label for="job-title">Job Title: </label>
        <input type="text" id="job-title" name="job_title" value="@Model.JobPosting.Title" />
    </div>

    <div class="form-row">
        <label for="job-desc">Job Description: </label>
        <textarea id="job-desc" name="job_desc">@Model.JobPosting.Description</textarea>
    </div>

    <div class="form-row">
        <label for="job-qual">Job Qualifications: </label>
        <textarea id="job-qual" name="job_qual">@Model.JobPosting.Qualifications</textarea>
    </div>

    <div class="form-row">
        <label>Deadline: </label>
        <input type="date" name="job_deadline_date" value="@Model.JobPosting.Deadline.ToString("yyyy/MM/dd")" />
        <input type="time" name="job_deadline_time" value="@Model.JobPosting.Deadline.ToString("HH:mm")" />
    </div>

    <div class="form-row">
        <label for="job-is-active">Is Active?: </label>
        @if (Model.JobPosting.IsActive)
        {<input type="checkbox" id="job-is-active" name="job_is_active" value="true" checked> }
        else
        { <input type="checkbox" id="job-is-active" name="job_is_active" value="true">}
    </div>

    <div class="form-row">
        <label for="job-department">Department:</label>
        <!-- Creates a dropdown list with all the departments -->
        <select id="job-department" name="job_department">
            @foreach (var department in Model.Departments)
            {
                @if (department.DepartmentID == Model.JobPosting.DepartmentID)
                {
                    <option value="@department.DepartmentID" selected>@department.Name</option>
                }
                else
                {
                    <option value="@department.DepartmentID">@department.Name</option>
                }
            }
        </select>
    </div>

    <div class="form-row">
        <input type="submit" value="Submit" />
    </div>
</form>

@Html.ActionLink("Back to List", "Index", "JobPosting")

HospitalProject/Views/JobPosting/Index.cshtml
@model IEnumerable<HospitalProject.Models.JobPosting>

@{
    ViewBag.Title = "Index";
}

<h2>Job Postings</h2>

<div class="recadd">
    <!-- Based off Christine's Example -->
    @{ //variable declaration id (will put user admin id into here)
        string id = "";
    }
    @if ((string)ViewData["UserHasAdmin"] == "False")
    {
        @Html.ActionLink("Add Admin", "Create", "Admin")
    }
    else if ((string)ViewData["UserHasAdmin"] == "None")
    {
        @Html.ActionLink("Register An Account", "Register", "Account")
    }
    else
    {
        @Html.ActionLink("Your Profile", "Details/" + (string)ViewData["UserHasAdmin"], "Admin")
        id = (string)ViewData["UserHasAdmin"];
        <div>
            @Html.ActionLink("Add a Job Posting", "Create", "JobPosting")
        </div>
    }

</div>
<div>
    <!-- From Christine's Pagination Notes -->
    @ViewData["PaginationSummary"]
    @Html.ActionLink("Prev", "Index", "JobPosting",
        new { pagenum= ((int)ViewData["pagenum"] - 1)}
        )
    |
    @Html.ActionLink("Next", "Index", "JobPosting",
        new { pagenum = ((int)ViewData["pagenum"] + 1) }
        )
</div>

<div class="jobs-area">
    @foreach (JobPosting jobPosting in Model)
    {
    <div class="job-posting">
        @if ((string)ViewData["UserHasAdmin"] != "False" && (string)ViewData["UserHasAdmin"] != "None")
        {
            <div>
                @Html.ActionLink("Edit", "Edit", new { id = jobPosting.JobPostingID, adminid = jobPosting.AdminID }) |
                @Html.ActionLink("Delete", "Delete", new { id = jobPosting.JobPostingID, adminid = jobPosting.AdminID })
            </div>
        }

        <div class="feature-heading">@Html.ActionLink(jobPosting.Title, "Details", new { id = jobPosting.JobPostingID, adminid = jobPosting.AdminID })</div>
        <div class="feature-description">Department: @jobPosting.Department.Name</div>
        <div class="feature-description">Description: @jobPosting.Description</div>
        <div class="feature-description">Qualifications: @jobPosting.Qualifications</div>
        <div class="feature-description">Deadline to Apply: @jobPosting.Deadline.ToString()</div>

        @if ((string)ViewData["UserHasAdmin"] != "False" && (string)ViewData["UserHasAdmin"] != "None")
        {
            <div class="feature-description">Is Active: @jobPosting.IsActive</div>
            <div class="feature-description">Created By: @jobPosting.Admin.FirstName @jobPosting.Admin.LastName</div>
        }
    </div>
    }
</div>